# Generated by Django 4.2.4 on 2023-08-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Published Videos', 'verbose_name_plural': 'Published Videos'},
        ),
    ]
