# Generated by Django 4.2.4 on 2023-08-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Publish'), ('DR', 'Draft'), ('UN', 'Unlisted')], default='DR', max_length=2),
        ),
    ]
