# Generated by Django 4.2.4 on 2023-08-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_tvseasionproxy_tvshowproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TVSeasionProxy',
        ),
        migrations.CreateModel(
            name='TVShowSeasionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
