# Generated by Django 4.2.4 on 2023-08-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_video_state'),
        ('playlists', '0003_playlist_videos_alter_playlist_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_playlist', to='videos.video'),
        ),
    ]
